### PR TITLE
IPython repr methods

### PR DESCRIPTION
**Pull request by varunagrawal**
This PR adds support for the various `_repr_*_` methods in IPython as detailed [here](https://ipython.readthedocs.io/en/stable/config/integrating.html).

Only the `_repr_mimetype_` method is not supported since that requires some special handling.

@dellaert the main unit test you need to look at is in `class.i` and the `class_pybind.cpp` and `class_py.cpp` files.

### CODE REVIEW

**Comment by varunagrawal** [comment]
I also unit-tested this in GTSAM and it works great. Only thing is that you can't pass in a lambda instead of a `KeyFormatter` so the nice alphabet printing doesn't yet happen.

**Comment by dellaert** [comment]
> Only thing is that you can't pass in a lambda instead of a `KeyFormatter` so the nice alphabet printing doesn't yet happen.

Why? It works if I wrap `_repr_markdown_`...

**Comment by dellaert** [comment]
Cool, but I think maybe you made it a bit too complicated, and as a result more restrictive. I think the only thing needed was a name change, e.g., from `markdown` to `_repr_markdown_`. I actually have plans to have versions with different arguments, so this approach does not work :-(

**Comment by varunagrawal** [comment]
Oh I see, you're right. I'll update it in a bit (feeling the effects of the booster).

**Comment by dellaert** [comment]
:-)

**Comment by varunagrawal** [comment]
@dellaert it is done, however I don't see a python example of `_repr_markdown_` in your other PR. Am I missing something?

**Comment by dellaert** [comment]
> @dellaert it is done, however I don't see a python example of `_repr_markdown_` in your other PR. Am I missing something?

Yeah, this is used mostly in the robotics2 book. I’ll add a test for good measure after this wrap has been merged into gtsam.

**Review by dellaert — APPROVED** [review]
Awesomesauce!!! Nice Christmas gift :-)

**Pull request merged**
