### PR TITLE
Miscellaneous Cleanup

### PR DESCRIPTION
**Pull request by varunagrawal**
1. Encapsulate the wrapping process into the single `wrap` method.
2. Removed unused imports.
3. Un-skip tests.
4. Formatting.

### CODE REVIEW

**Comment by varunagrawal** [comment]
I still don't get the point of the docgen stuff. Can't we just generate documentation from the docstrings directly instead of having dedicated code for this?

**Comment by ProfFan** [comment]
I thought so (and prototyped a libclang thing to parse the C++ docstrings), but Frank thinks that we should not waste time and reuse the old code...

**Comment by varunagrawal** [comment]
Huh I was suggesting doxygen but yeah low priority

**Comment by ProfFan** [comment]
docgen is using doxygen XML files to generate Python documentation (that can be displayed in autocomplete)

**Comment by dellaert** [comment]
Please use doxygen no Michael’s code to generate the python wrappers

**Comment by dellaert** [comment]
As we discussed

**Pull request merged**
