### PR TITLE
Support multiple files for Pybind11 wrapper

### LINKED ISSUE #44: Optimization
We need to split the interface files to optimize the build time and memory.

https://pybind11.readthedocs.io/en/latest/faq.html#how-can-i-reduce-the-build-time
https://pybind11.readthedocs.io/en/latest/advanced/classes.html#module-local-class-bindings

https://github.com/pybind/pybind11/issues/1934

### PR DESCRIPTION
**Pull request by varunagrawal**
This resolves #44.

### CODE REVIEW

**Comment by ProfFan** [comment]
This is great! Friendly reminder that the smoking test should be updated to reflect this change.

**Comment by varunagrawal** [comment]
Do we have a smoke test for the wrapper? I've been updating the template project in order to test this out, but I totally agree with you on this aspect.

**Comment by ProfFan** [comment]
Sorry I just realized that we have been testing the wrapper manually all the way 🤣. Maybe just add one more header to `tests` and in `test_pybind_wrapper` use the multi-file generation routine you just made?

(Yeah we should have a smoking test, maybe an Action building latest example project against `gtwrap`. A TODO though.

**Review by ProfFan — APPROVED** [review]
LGTM :)

Most significant concern is in linking. But we cannot tell unless we arrive at GTSAM CI.

**Pull request merged**
