### PR TITLE
CMake Updates

### PR DESCRIPTION
**Pull request by varunagrawal**
1. Made `WRAP_PYTHON_VERSION` optional.
2. Added more status messages detailing installation locations.

### CODE REVIEW

**Review by ProfFan — APPROVED** [review]
Could you also test with a prefix-based install and paste here the `tree <prefix>` result?

**Comment by varunagrawal** [comment]
@ProfFan great suggestion. I found and fixed a bug.

Also, here's the output of `tree <prefix>`

```sh
install
├── bin
│   ├── matlab_wrap.py
│   └── pybind_wrap.py
├── include
│   └── gtwrap
│       └── matlab.h
└── lib
    ├── cmake
    │   └── gtwrap
    │       ├── gtwrapConfig.cmake
    │       ├── GtwrapUtils.cmake
    │       ├── MatlabWrap.cmake
    │       └── PybindWrap.cmake
    └── gtwrap
        ├── gtwrap
        │   ├── __init__.py
        │   ├── interface_parser
        │   │   ├── classes.py
        │   │   ├── declaration.py
        │   │   ├── function.py
        │   │   ├── __init__.py
        │   │   ├── module.py
        │   │   ├── namespace.py
        │   │   ├── __pycache__
        │   │   │   ├── classes.cpython-38.pyc
        │   │   │   ├── declaration.cpython-38.pyc
        │   │   │   ├── function.cpython-38.pyc
        │   │   │   ├── __init__.cpython-38.pyc
        │   │   │   ├── interface_parser.cpython-38.pyc
        │   │   │   ├── module.cpython-38.pyc
        │   │   │   ├── namespace.cpython-38.pyc
        │   │   │   ├── template.cpython-38.pyc
        │   │   │   ├── tokens.cpython-38.pyc
        │   │   │   └── type.cpython-38.pyc
        │   │   ├── template.py
        │   │   ├── tokens.py
        │   │   └── type.py
        │   ├── matlab_wrapper.py
        │   ├── matlab_wrapper.tpl
        │   ├── pybind_wrapper.py
        │   ├── __pycache__
        │   │   ├── __init__.cpython-36.pyc
        │   │   ├── __init__.cpython-38.pyc
        │   │   ├── interface_parser.cpython-36.pyc
        │   │   ├── interface_parser.cpython-38.pyc
        │   │   ├── interface_parser.cpython-38-pytest-6.2.1.pyc
        │   │   ├── matlab_wrapper.cpython-36.pyc
        │   │   ├── matlab_wrapper.cpython-38.pyc
        │   │   ├── matlab_wrapper.cpython-38-pytest-6.2.1.pyc
        │   │   ├── pybind_wrapper.cpython-36.pyc
        │   │   ├── pybind_wrapper.cpython-38.pyc
        │   │   ├── pybind_wrapper.cpython-38-pytest-6.2.1.pyc
        │   │   ├── template_instantiator.cpython-36.pyc
        │   │   └── template_instantiator.cpython-38.pyc
        │   ├── template_instantiator.py
        │   └── test.py
        └── pybind11
            ├── CMakeLists.txt
            ├── docs
            │   ├── advanced
            │   │   ├── cast
            │   │   │   ├── chrono.rst
            │   │   │   ├── custom.rst
            │   │   │   ├── eigen.rst
            │   │   │   ├── functional.rst
            │   │   │   ├── index.rst
            │   │   │   ├── overview.rst
            │   │   │   ├── stl.rst
            │   │   │   └── strings.rst
            │   │   ├── classes.rst
            │   │   ├── embedding.rst
            │   │   ├── exceptions.rst
            │   │   ├── functions.rst
            │   │   ├── misc.rst
            │   │   ├── pycpp
            │   │   │   ├── index.rst
            │   │   │   ├── numpy.rst
            │   │   │   ├── object.rst
            │   │   │   └── utilities.rst
            │   │   └── smart_ptrs.rst
            │   ├── basics.rst
            │   ├── benchmark.py
            │   ├── benchmark.rst
            │   ├── changelog.rst
            │   ├── classes.rst
            │   ├── compiling.rst
            │   ├── conf.py
            │   ├── Doxyfile
            │   ├── faq.rst
            │   ├── index.rst
            │   ├── intro.rst
            │   ├── limitations.rst
            │   ├── Makefile
            │   ├── pybind11-logo.png
            │   ├── pybind11_vs_boost_python1.png
            │   ├── pybind11_vs_boost_python1.svg
            │   ├── pybind11_vs_boost_python2.png
            │   ├── pybind11_vs_boost_python2.svg
            │   ├── reference.rst
            │   ├── release.rst
            │   ├── requirements.txt
            │   ├── _static
            │   │   └── theme_overrides.css
            │   └── upgrade.rst
            ├── include
            │   └── pybind11
            │       ├── attr.h
            │       ├── buffer_info.h
            │       ├── cast.h
            │       ├── chrono.h
            │       ├── common.h
            │       ├── complex.h
            │       ├── detail
            │       │   ├── class.h
            │       │   ├── common.h
            │       │   ├── descr.h
            │       │   ├── init.h
            │       │   ├── internals.h
            │       │   └── typeid.h
            │       ├── eigen.h
            │       ├── embed.h
            │       ├── eval.h
            │       ├── functional.h
            │       ├── iostream.h
            │       ├── numpy.h
            │       ├── operators.h
            │       ├── options.h
            │       ├── pybind11.h
            │       ├── pytypes.h
            │       ├── stl_bind.h
            │       └── stl.h
            ├── LICENSE
            ├── MANIFEST.in
            ├── pybind11
            │   ├── commands.py
            │   ├── __init__.py
            │   ├── __main__.py
            │   ├── setup_helpers.py
            │   └── _version.py
            ├── pyproject.toml
            ├── README.md
            ├── setup.cfg
            ├── setup.py
            ├── tests
            │   ├── CMakeLists.txt
            │   ├── conftest.py
            │   ├── constructor_stats.h
            │   ├── cross_module_gil_utils.cpp
            │   ├── env.py
            │   ├── extra_python_package
            │   │   ├── pytest.ini
            │   │   └── test_files.py
            │   ├── extra_setuptools
            │   │   ├── pytest.ini
            │   │   └── test_setuphelper.py
            │   ├── local_bindings.h
            │   ├── object.h
            │   ├── pybind11_cross_module_tests.cpp
            │   ├── pybind11_tests.cpp
            │   ├── pybind11_tests.h
            │   ├── __pycache__
            │   │   ├── conftest.cpython-38-pytest-6.1.2.pyc
            │   │   ├── conftest.cpython-38-pytest-6.2.1.pyc
            │   │   └── env.cpython-38.pyc
            │   ├── pytest.ini
            │   ├── requirements.txt
            │   ├── test_async.cpp
            │   ├── test_async.py
            │   ├── test_buffers.cpp
            │   ├── test_buffers.py
            │   ├── test_builtin_casters.cpp
            │   ├── test_builtin_casters.py
            │   ├── test_callbacks.cpp
            │   ├── test_callbacks.py
            │   ├── test_call_policies.cpp
            │   ├── test_call_policies.py
            │   ├── test_chrono.cpp
            │   ├── test_chrono.py
            │   ├── test_class.cpp
            │   ├── test_class.py
            │   ├── test_cmake_build
            │   │   ├── CMakeLists.txt
            │   │   ├── embed.cpp
            │   │   ├── installed_embed
            │   │   │   └── CMakeLists.txt
            │   │   ├── installed_function
            │   │   │   └── CMakeLists.txt
            │   │   ├── installed_target
            │   │   │   └── CMakeLists.txt
            │   │   ├── main.cpp
            │   │   ├── subdirectory_embed
            │   │   │   └── CMakeLists.txt
            │   │   ├── subdirectory_function
            │   │   │   └── CMakeLists.txt
            │   │   ├── subdirectory_target
            │   │   │   └── CMakeLists.txt
            │   │   └── test.py
            │   ├── test_constants_and_functions.cpp
            │   ├── test_constants_and_functions.py
            │   ├── test_copy_move.cpp
            │   ├── test_copy_move.py
            │   ├── test_custom_type_casters.cpp
            │   ├── test_custom_type_casters.py
            │   ├── test_docstring_options.cpp
            │   ├── test_docstring_options.py
            │   ├── test_eigen.cpp
            │   ├── test_eigen.py
            │   ├── test_embed
            │   │   ├── catch.cpp
            │   │   ├── CMakeLists.txt
            │   │   ├── external_module.cpp
            │   │   ├── test_interpreter.cpp
            │   │   └── test_interpreter.py
            │   ├── test_enum.cpp
            │   ├── test_enum.py
            │   ├── test_eval_call.py
            │   ├── test_eval.cpp
            │   ├── test_eval.py
            │   ├── test_exceptions.cpp
            │   ├── test_exceptions.py
            │   ├── test_factory_constructors.cpp
            │   ├── test_factory_constructors.py
            │   ├── test_gil_scoped.cpp
            │   ├── test_gil_scoped.py
            │   ├── test_iostream.cpp
            │   ├── test_iostream.py
            │   ├── test_kwargs_and_defaults.cpp
            │   ├── test_kwargs_and_defaults.py
            │   ├── test_local_bindings.cpp
            │   ├── test_local_bindings.py
            │   ├── test_methods_and_attributes.cpp
            │   ├── test_methods_and_attributes.py
            │   ├── test_modules.cpp
            │   ├── test_modules.py
            │   ├── test_multiple_inheritance.cpp
            │   ├── test_multiple_inheritance.py
            │   ├── test_numpy_array.cpp
            │   ├── test_numpy_array.py
            │   ├── test_numpy_dtypes.cpp
            │   ├── test_numpy_dtypes.py
            │   ├── test_numpy_vectorize.cpp
            │   ├── test_numpy_vectorize.py
            │   ├── test_opaque_types.cpp
            │   ├── test_opaque_types.py
            │   ├── test_operator_overloading.cpp
            │   ├── test_operator_overloading.py
            │   ├── test_pickling.cpp
            │   ├── test_pickling.py
            │   ├── test_pytypes.cpp
            │   ├── test_pytypes.py
            │   ├── test_sequences_and_iterators.cpp
            │   ├── test_sequences_and_iterators.py
            │   ├── test_smart_ptr.cpp
            │   ├── test_smart_ptr.py
            │   ├── test_stl_binders.cpp
            │   ├── test_stl_binders.py
            │   ├── test_stl.cpp
            │   ├── test_stl.py
            │   ├── test_tagbased_polymorphic.cpp
            │   ├── test_tagbased_polymorphic.py
            │   ├── test_union.cpp
            │   ├── test_union.py
            │   ├── test_virtual_functions.cpp
            │   └── test_virtual_functions.py
            └── tools
                ├── check-style.sh
                ├── cmake_uninstall.cmake.in
                ├── FindCatch.cmake
                ├── FindEigen3.cmake
                ├── FindPythonLibsNew.cmake
                ├── libsize.py
                ├── pybind11Common.cmake
                ├── pybind11Config.cmake.in
                ├── pybind11NewTools.cmake
                ├── pybind11Tools.cmake
                ├── pyproject.toml
                ├── setup_global.py.in
                └── setup_main.py.in

34 directories, 244 files
```

**Comment by varunagrawal** [comment]
Can you please confirm if it looks good? I'll merge then.

**Comment by ProfFan** [comment]
LGTM :)

**Pull request merged**
