### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by ProfFan**
I copied the LICENSE.BSD from GTSAM, is it appropriate for this repo? @dellaert for final confirmation.

### CODE REVIEW

**Review by dellaert — APPROVED** [review]
Is that BSD? Did you copy everything relevant from GTSAM?

**Comment by ProfFan** [comment]
Yes, since this is only GTSAM code we only need the BSD part.

**Comment by ProfFan** [comment]
@dellaert Should we keep the GTRC name or use the lab name?

**Comment by dellaert** [comment]
GTRC

**Pull request merged**
