### PR TITLE
Remove reference from shared pointers

### PR DESCRIPTION
**Pull request by varunagrawal**
Found a bug in `TemplateType` where adding shared pointers as a reference in the template parameters causes the C++ compiler to complain.

This PR fixes that by adding a flag that exclusively says not to add a reference (`T&`) when inserting shared pointers as template parameters.

### CODE REVIEW

**Comment by ProfFan** [comment]
I think we need some 2nd thoughts on this. Is this the root problem?

**Comment by dellaert** [comment]
Maybe explain the issue a little bit better?

**Comment by varunagrawal** [comment]
Sure. Currently we follow the best practice of converting `T*` to `shared_ptr<T>&` i.e. a reference to a shared pointer.

In order to pass in and return data types like `std::vector<T*>`, I added the `TemplateType` parsing rule which will give us `std::vector<boost::shared_ptr<T>&>` (if we use Boost).

However, when compiling, this gives us the following error:

```
/home/varun/borglab/GTDynamics/build/python/gtdynamics.cpp:237:174:   required from here
/usr/local/lib/gtwrap/pybind11/include/pybind11/detail/init.h:63:64: error: no matching function for call to ‘gtdynamics::Robot::Robot(<brace-enclosed initializer list>)’
   63 | inline Class *construct_or_initialize(Args &&...args) { return new Class{std::forward<Args>(args)...}; }
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/varun/borglab/GTDynamics/build/python/gtdynamics.cpp:32:
/home/varun/borglab/GTDynamics/gtdynamics/universal_robot/Robot.h:67:12: note: candidate: ‘gtdynamics::Robot::Robot(const LinkMap&, const JointMap&)’
   67 |   explicit Robot(const LinkMap &links, const JointMap &joints);
      |            ^~~~~
/home/varun/borglab/GTDynamics/gtdynamics/universal_robot/Robot.h:67:33: note:   no known conversion for argument 1 from ‘std::map<std::__cxx11::basic_string<char>, boost::shared_ptr<gtdynamics::Link>&>’ to ‘const LinkMap&’ {aka ‘const std::map<std::__cxx11::basic_string<char>, boost::shared_ptr<gtdynamics::Link> >&’}
```

This is because in GTDynamics, 
```cpp
Robot(std::map<string, gtdynamics::Link*> links, std::map<string, gtdynamics::Joint*> joints);
```

gives us
```cpp
.def(py::init<std::map<string, boost::shared_ptr<gtdynamics::Link>&>, std::map<string, boost::shared_ptr<gtdynamics::Joint>&>>(), py::arg("links"), py::arg("joints"))
```

If we remove the `&` in the `std::map` template arguments, it works because the error specifically says

```
no known conversion for argument 1 from ‘std::map<std::__cxx11::basic_string<char>, boost::shared_ptr<gtdynamics::Link>&>’ to ‘const LinkMap&’ {aka ‘const std::map<std::__cxx11::basic_string<char>, boost::shared_ptr<gtdynamics::Link> >&’}
```

**Review by dellaert — CHANGES_REQUESTED** [review]
Re-request after changes from our meeting.

**Review by dellaert — APPROVED** [review]

**Pull request merged**
